- name: Wordpress Setup
  hosts: pm01
  become: yes

  tasks:
    - name: Download WordPress template
      command: pveam download local debian-12-turnkey-wordpress_18.2-1_amd64.tar.gz
      become: yes

    - name: Create 10 WordPress containers
      shell: >
        pct create {{ item }} local:vztmpl/debian-12-turnkey-wordpress_18.2-1_amd64.tar.gz
        --cores 1
        --hostname wordpress{{ item }}
        --memory 1024
        --net0 name=eth0,bridge=vmbr0,firewall=1,ip=10.24.17.{{ item }}/16,gw=10.24.17.1,rate=400
        --rootfs cluster_ceph_pool:30
        --password "proxmox"
        --swap 0
        --features nesting=1
      with_sequence: start=101 end=110
      become: yes

    - name: Check storage
      command: pct fsck {{ item }}
      with_sequence: start=101 end=110

    - name: Start the containers
      shell: pct start {{ item }}
      with_sequence: start=101 end=110