---
- name: Install swarm dependencies and create cluster (if needed)
  hosts: docker
  become: yes

  tasks:
    - name: Install python3-docker (if needed)
      apt:
        name: python3-docker
        state: present
      become: yes

    - name: Initialize Docker Swarm (if not already initialized)
      community.general.docker_swarm:
        state: present
        advertise_addr: "10.24.17.61" #opzetten swarm op docker VM1
      register: swarm_init_result

    - name: Extract Swarm Manager Join Command (if created)
      set_fact:
        swarm_manager_join_command: "{{ swarm_init_result.swarm_facts.JoinTokens.Manager }}"
      when: swarm_init_result is defined and swarm_init_result.changed

- name: Deploy docker service (on swarm manager)
  hosts: ansible@10.24.17.61  # Target the swarm manager node
  become: yes

  tasks:
    - name: Run the Docker container as a Swarm service
      community.general.docker_swarm_service:
        name: lessen-7
        image: image7
        command: ping docker.com
        state: present
